package mobemu.algorithms;


import mobemu.node.Context;
import mobemu.node.Message;
import mobemu.node.Node;
import mobemu.utils.Ant;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AntRouter extends Node {

    /**
     * Size of a node's ant memory.
     */
    private static Integer antMemorySize = null;

    /**
     * Ants that either reached this node or were generated by it (and are not yet forwarded).
     * Ants travel to nodes and do not get stored, carried or multiplied. They walk and gather information about the
     * nodes on the path they ended up taking in the hopes of finding the final destination.
     * If the final destination is found, an ant returns to it's source in order to deliver the path it took.
     * If the final destination is not found, the ant returns with the information of the most socially strong
     * encountered nodes that can act as a better relay for the destination.
     */
    private List<Ant.AntMessage> antMemory;

    /**
     * Instantiates a {@code AntRouter} object.
     *
     * @param id ID of the node
     * @param nodes total number of existing nodes
     * @param context the context of this node
     * @param socialNetwork the social network as seen by this node
     * @param dataMemorySize the maximum allowed size of the data memory
     * @param exchangeHistorySize the maximum allowed size of the exchange history
     * @param seed the seed for the random number generators
     * @param traceStart timestamp of the start of the trace
     * @param traceEnd timestamp of the end of the trace
     */
    public AntRouter(int id, int nodes, Context context, boolean[] socialNetwork, int dataMemorySize,
                     int exchangeHistorySize, long seed, long traceStart, long traceEnd, int antMemorySize) {
        super(id, nodes, context, socialNetwork, dataMemorySize, exchangeHistorySize, seed, traceStart, traceEnd);

        if (AntRouter.antMemorySize == null) {
            AntRouter.antMemorySize = antMemorySize;
        }
    }

    @Override
    public String getName() { return "AntRouter"; }

    @Override
    public void onDataExchange(Node encounteredNode, long contactDuration, long currentTime) {
        // Check and cast to the AntRouter instance
        if (!(encounteredNode instanceof AntRouter)) {
            return;
        }

        AntRouter antRouterEncounteredNode = (AntRouter) encounteredNode;

        // Perform the delivery of messages that are destined for the current node
        int remainingMessages = deliverDirectMessages(antRouterEncounteredNode, false, contactDuration, currentTime, false);
        int totalMessages = 0;

        // I am here trying to decide if it's better to forward ants in an epidemic way or where do i
        //establish how many ants i send into the network
        // R: ok i think if i am the source node i establish the number of Ants i am going to send
        // and then the relay nodes never think about this, if the receive an ant to forward they simply
        // do so in an epidemic way
        // how to prevent the ants from visiting the exact same nodes on the exact same paths? idk

        // Analyze messages of the encountered node's data memory and apply algorithm
        for (Message message : antRouterEncounteredNode.dataMemory) {
            // Assure that network capacity is not exceeded
            if (totalMessages >= remainingMessages) {
                return;
            }

            // AntRouter mechanism to decide which messages are downloaded

            if (!message.isDelivered(encounteredNode.getId())) {
                // send Forward Ants to explore paths

            }
        }

        // Analyze messages of the encountered node's own memory and apply algorithm
        for (Message message : antRouterEncounteredNode.ownMessages) {
            // Assure that network capacity is not exceeded
            if (totalMessages >= remainingMessages) {
                return;
            }

            // AntRouter mechanism to decide which messages are downloaded
        }

    }

//    @Override
//    protected boolean insertMessage(Message message, Node from, long currentTime, boolean altruism, boolean dissemination) {
//        if (message instanceof AntMessage) {
//            // Store Ant Messages in antMemory (separately from normal messages)
//            if (!antMemory.contains(message)) {
//                antMemory.add((AntMessage) message);
//            }
//
//            // Return successful storage and don't include ant in the rest of statistics mobemu computes for normal messages
//            return true;
//        }
//
//        // Normal messages are still tracked by mobemu
//        return super.insertMessage(message, from, currentTime, altruism, dissemination);
//
//    }
}
