package mobemu.algorithms;

import mobemu.node.Context;
import mobemu.node.Message;
import mobemu.node.Node;
import mobemu.utils.Ant;

import java.util.*;

/**
 * Class for Ant-driven Social Relay Routing Algorithm node.
 *
 * Nodes update pheromone levels based on ants forwarding.
 * If destination is found, continue classic ARA.
 * If destination is not found, return ants with a list of the best
 * relays (socially) and send the message to these nodes.
 * Maybe the source will never directly encounter the source through ARA
 * but a node socially related to it will.
 */
public class ASRRA extends Node {
    /**
     * Size of a node's ant memory.
     */
    private static Integer antMemorySize = null;

    /**
     * Ants that either reached this node or were generated by it (and are not yet forwarded).
     * Ants travel to nodes and do not get stored, carried or multiplied. They walk and gather information about the
     * nodes on the path they ended up taking in the hopes of finding the final destination.
     * If the final destination is found, an ant returns to it's source in order to deliver the path it took.
     * If the final destination is not found, the ant returns with the information of the most socially strong
     * encountered nodes that can act as a better relay for the destination.
     */
    private List<Ant.AntMessage> antMemory;

    /**
     * Default pheromone value for each node
     */
    private static final double INITIAL_PHEROMONE = 1.0;
    /**
     * The pheromone decay rate each node loses on each tick
     */
    private static final double EVAPORATION_RATE = 0.1;
    /**
     * The pheromone boost that an encountered node receives upon contact
     */
    private static final double PHEROMONE_BOOST = 2.0;
    /**
     * Random value for pheromone computations
     */
    private static Random pheromoneRandom = null;

    /**
     * Map for every encountered node id and the node's pheromone level as seen by
     * the current node.
     */
    private Map<Integer, Double> pheromoneTable;

    /**
     * Instantiates a {@code ASRRA} object.
     *
     * @param id ID of the node
     * @param nodes total number of existing nodes
     * @param context the context of this node
     * @param socialNetwork the social network as seen by this node
     * @param dataMemorySize the maximum allowed size of the data memory
     * @param exchangeHistorySize the maximum allowed size of the exchange history
     * @param seed the seed for the random number generators
     * @param traceStart timestamp of the start of the trace
     * @param traceEnd timestamp of the end of the trace
     */
    public ASRRA(int id, int nodes, Context context, boolean[] socialNetwork, int dataMemorySize, int exchangeHistorySize, long seed, long traceStart, long traceEnd, int antMemorySize) {
        super(id, nodes, context, socialNetwork, dataMemorySize, exchangeHistorySize, seed, traceStart, traceEnd);

        this.pheromoneTable = new HashMap<>();
        this.pheromoneRandom = new Random(seed);

        if (ASRRA.antMemorySize == null) {
            ASRRA.antMemorySize = antMemorySize;
        }

        this.antMemory = new ArrayList<>(Collections.nCopies(antMemorySize, new Ant.AntMessage(-1, -1, -1, -1)));
    }

    @Override
    public String getName() { return "Ant-driven Social Relay Routing Algorithm"; }

    @Override
    public void onDataExchange(Node encounteredNode, long contactDuration, long currentTime) {
        // Check and cast to the ASRRA instance
        if (!(encounteredNode instanceof ASRRA)) {
            return;
        }

        ASRRA asrraEncounteredNode = (ASRRA) encounteredNode;

        // Perform the delivery of messages that are destined for the current node
        int remainingMessages = deliverDirectMessages(asrraEncounteredNode, false, contactDuration, currentTime, false);
        int totalMessages = 0;

        // Analyze messages of the encountered node's data memory
        for (Ant.AntMessage ant : asrraEncounteredNode.antMemory) {
            //if fant take it and update pheromone values
            //if bant ?
            processAnt(ant, asrraEncounteredNode);
        }

        // Analyze messages of the encountered node's data memory and apply algorithm
        for (Message message : asrraEncounteredNode.dataMemory) {
            // Assure that network capacity is not exceeded
            if (totalMessages >= remainingMessages) {
                return;
            }

            // ACO mechanism to decide which messages are downloaded
//            if (shouldForwardMessage(message, asrraEncounteredNode)) {
//                if (insertMessage(message, asrraEncounteredNode, currentTime, false, false)) {
//                    totalMessages++;
//                }
//            }
        }

        // Analyze messages of the encountered node's own memory and apply algorithm
        for (Message message : asrraEncounteredNode.ownMessages) {
            // Assure that network capacity is not exceeded
            if (totalMessages >= remainingMessages) {
                return;
            }

            // ACO mechanism to decide which messages are downloaded
//            if (shouldForwardMessage(message, asrraEncounteredNode)) {
//                if (insertMessage(message, asrraEncounteredNode, currentTime, false, false)) {
//                    totalMessages++;
//                }
//            }
        }
    }

    /**
     * When a message is generated, forward ants will be launched in order to search for the
     * destination of the message.
     */
    @Override
    public Message generateMessage(Message message) {
        ownMessages.add(message);

        // Create Forward Ant for route discovery
        // TODO: sort out what i need to do with the antID
        Ant.AntMessage fant = new Ant.AntMessage(message.getId(), message.getId(), this.id, message.getDestination());

        antMemory.add(fant);
        //forwardAnt(fant);

        return message;
    }

    // to be able to process logic that happens even if current contacts are not disrupted can
    // override th run method of a node
    @Override
    public void run(Node encounteredNode, long tick, long contactDuration, boolean newContact, long timeDelta, long sampleTime) {
        super.run(encounteredNode, tick, contactDuration, newContact, timeDelta, sampleTime);

        /*ok so here insert the logix that need to be applied even if two nodes are still in contact
        but the antMemory was modified, i guess i need to implement some sort of observer that notifies
        the source node that antMemory was updated by someone else and that the newly received ant or ants
        need to be processed.
        Maybe i should separate the bacward ants memory from the forward ant memory for even more clarity
        and even less cheching as wel as making multiple classes that are different for each type of ant
        so we respect the separation of concerns
         */
    }

    /**
     * Process and ant
     * @param ant
     * @param asrraEncounteredNode
     */
    private void processAnt(Ant.AntMessage ant, ASRRA asrraEncounteredNode) {
        Ant.AntMessageInfo antInfo = ant.getInfo();

        // Avoid loops by not revisiting the same nodes as a forward ant
        if (antInfo.getPath().contains(id) && !antInfo.isBackwardAnt()) {
            return;
        }

        // Add current node to the ant's path and update pheromone levels accordingly
        antInfo.addToPath(id);
        updatePheromone(antInfo.getOwner(), PHEROMONE_BOOST);

        // If ant reached message destination, convert to BANT
        if (id == antInfo.getDestination()) {
            antInfo.setReachedDestination(true);
            convertToBant(ant);
        }

    }

    /**
     * Evaporates pheromone values over time to prevent over-concentration on certain paths.
     */
    @Override
    protected void onTick(long currentTime, long sampleTime) {
        super.onTick(currentTime, sampleTime);

        for (Map.Entry<Integer, Double> entry : pheromoneTable.entrySet()) {
            pheromoneTable.put(entry.getKey(), entry.getValue() * (1 - EVAPORATION_RATE));
        }
    }

    private void updatePheromone(int nodeId, double boost) {
        double currentPheromone = pheromoneTable.getOrDefault(nodeId, INITIAL_PHEROMONE);
        pheromoneTable.put(nodeId, currentPheromone + boost);
    }

    private void convertToBant(Ant.AntMessage ant) {
        // Create a backward ant to return to source taking the path discovered by the source
        Ant.AntMessage bant = new Ant.AntMessage(ant.getAntId(), ant.getInfo().getMessageId(), ant.getSource(), ant.getDestination());
        bant.getInfo().setBackwardAnt(true);

        forwardBant(bant);
    }

    private void forwardBant(Ant.AntMessage bant) {
        List<Integer> path = bant.getInfo().getPath();

        if (path.size() < 2) return;

        // The previous node in the path fant took is the next hop for the bant
        int previousNode = path.get(path.indexOf(id) - 1);

        this.antMemory.add(bant);

        //ASRRA nextBantHop = (ASRRA) getNodeById(previousNode);

    }

}
